import * as fs from "node:fs";
import * as path from "node:path";
import type { TAnatomy, TSchema } from "../packages/paleui/src/shared/types";

const SITE_PAGES = path.resolve(
	import.meta.dirname,
	"../packages/site/src/pages/components",
);
const PALEUI_UI = path.resolve(
	import.meta.dirname,
	"../packages/paleui/src/ui",
);
const PALEUI_SHARED = path.resolve(
	import.meta.dirname,
	"../packages/paleui/src/shared",
);
const WATCH_MODE = process.argv.includes("--watch");

function generateAnatomyDescription(anatomy: TAnatomy): string[] {
	const descriptions: string[] = [];

	for (const root of Object.values(anatomy)) {
		if (root.description) {
			descriptions.push(...root.description);
		} else {
			const sel =
				typeof root.selector === "string" ? root.selector : root.selector[0];
			descriptions.push(`Built on the <code>&lt;${sel}&gt;</code> element.`);
		}

		if (!root.children) continue;

		for (const child of Object.values(root.children)) {
			if (child.type === "pseudo" || child.type === "text") continue;
			const childSel = (child.selector || "")
				.replace(/</g, "&lt;")
				.replace(/>/g, "&gt;");
			const opt = child.optional ? " (optional)" : "";
			descriptions.push(
				`<code>${childSel}</code> — ${child.description.join(" ")}${opt}.`,
			);
		}
	}

	return descriptions;
}

function generateStructureSection(schema: TSchema): string {
	if (!schema.anatomy) return "";

	const roots = Object.values(schema.anatomy);
	const descriptions = generateAnatomyDescription(schema.anatomy);
	const example = roots.find((r) => r.example)?.example;

	if (descriptions.length === 0 && !example) return "";

	const aboveSlot =
		descriptions.length > 0
			? `<Fragment slot="above">${descriptions.map((d) => `<p>${d}</p>`).join("")}</Fragment>`
			: "";

	return `<Section title="Structure"><Subsection>${aboveSlot}${example || ""}</Subsection></Section>`;
}

function generateDocsFromSchema(mod: { schema: TSchema }) {
	const { schema } = mod;
	if (
		!schema?.meta ||
		!schema?.examples ||
		!schema?.dimensions ||
		!schema?.states
	) {
		return null;
	}

	const { meta, dimensions, states, examples } = schema;

	const dimensionEntries = Object.values(dimensions);
	const sections = dimensionEntries.map((dim, i) => ({
		title: dim.meta?.title || "Options",
		description: dim.meta?.description,
		examples: examples[i] || [],
	}));

	if (examples.length > dimensionEntries.length) {
		sections.push({
			title: states.meta?.title || "States",
			description: states.meta?.description || [
				"Use <code>disabled</code> and <code>aria-busy</code> attributes to indicate status.",
			],
			examples: examples[dimensionEntries.length],
		});
	}

	const structureSection = generateStructureSection(schema);

	return { meta, sections, structureSection };
}

async function generateDocs(mod: { schema: TSchema }, componentName: string) {
	console.log(`Generating documentation for ${componentName}...`);

	const docs = generateDocsFromSchema(mod);
	if (!docs) {
		console.log(`⊘ Skipping ${componentName} (no schema/examples export)`);
		return;
	}

	const { meta, sections, structureSection } = docs;

	const belowSlot = meta.description?.length
		? `<Fragment slot="below">${meta.description.map((d: string) => `<p>${d}</p>`).join("")}</Fragment>`
		: "";

	const examplesSection =
		sections.length > 0
			? `<Section title="Examples">${sections
					.map((section) => {
						const above = section.description
							? `<Fragment slot="above">${section.description.map((n: string) => `<p>${n}</p>`).join("")}</Fragment>`
							: "";
						return `<Subsection title="${section.title}">${above}${section.examples.join("")}</Subsection>`;
					})
					.join("")}</Section>`
			: "";

	const astro = `---
// AUTO-GENERATED BY GENERATE-DOCS.TS
// DO NOT EDIT
import Header from "@/components/Header.astro";
import Section from "@/components/Section.astro";
import Subsection from "@/components/Subsection.astro";
import SideLayout from "../../layouts/SideLayout.astro";
---
<SideLayout title="${meta.title} - PaleUI">
<Header title="${meta.title}" subtitle="${meta.subtitle}" links={${JSON.stringify(meta.tags || [])}}>
${sections[0]?.examples?.[0] || ""}${belowSlot}
</Header>
${structureSection}${examplesSection}
</SideLayout>
`;

	const outputFile = path.join(SITE_PAGES, `${componentName}.astro`);

	fs.writeFileSync(outputFile, astro, "utf-8");
	console.log(`✓ Generated: ${outputFile}`);
}

async function generateAllDocs() {
	const files = fs.readdirSync(PALEUI_UI);
	const componentFiles = files.filter(
		(file) => file.endsWith(".ts") && !file.startsWith("_"),
	);

	let generated = 0;
	for (const file of componentFiles) {
		const componentName = path.basename(file, ".ts");
		try {
			const mod = await import(
				`../packages/paleui/src/ui/${componentName}.ts?t=${Date.now()}`
			);
			await generateDocs(mod, componentName);
			generated++;
		} catch (error) {
			console.error(`✗ Error processing ${componentName}:`, error);
		}
	}

	return generated;
}

if (WATCH_MODE) {
	console.log("Watching for changes in paleui/src/ui/*.ts and shared/*.ts...\n");
	generateAllDocs();

	fs.watch(PALEUI_UI, { recursive: true }, async (_, filename) => {
		if (filename?.endsWith(".ts") && !filename.startsWith("_")) {
			await generateAllDocs();
		}
	});

	fs.watch(PALEUI_SHARED, { recursive: true }, async (_, filename) => {
		if (filename?.endsWith(".ts")) {
			await generateAllDocs();
		}
	});
} else {
	console.log("Discovering component files...\n");
	const generated = await generateAllDocs();
	console.log(`\nDone! Generated ${generated} doc(s).`);
}
